#!/usr/bin/expect -f
set timeout 10
spawn ssh -o StrictHostKeyChecking=no administrator@110.78.210.133
expect "*assword:*"
send "P@ssw0rd1234\r"
expect "*$*"
send "sudo docker exec -i astro_db_uat mysql -uastro -ppassword123 psu_backend -e \"INSERT INTO \\\`user\\\` VALUES (12,'developer','dev1234','dev@intelligist.co.th','Developer','System','Dev','2026-05-07 14:00:00',1,2,'active','0000-00-00 00:00:00','dev1234','PASS123',1,NULL,NULL,NULL,0,'off','2026-05-07 14:00:00',NULL);\"\r"
expect {
    "*assword*" {
        send "P@ssw0rd1234\r"
        expect "*$*"
    }
    "*$*" {}
}
send "exit\r"
expect eof
