#!/usr/bin/expect -f
set timeout 60
set host "110.78.210.128"
set user "administrator"
set pass "P@ssw0rd1234"
set sql [lindex $argv 0]

spawn ssh -t $user@$host "sudo docker exec astro_db_uat mysql -uastro -ppassword123 psu_backend -e \"$sql\""
expect {
    "password for administrator:" {
        send "$pass\r"
        exp_continue
    }
    "password:" {
        send "$pass\r"
        exp_continue
    }
    eof
}
