import oracledb

password = 'Coj@4321'
config_dir = '/app/Wallet_L2EPRDDB'
dsn = 'l2eprddb_high'

usernames = """ACADEMY_APP_PROD
ACADEMY_OWNER_PROD
ADBSNMP
ADB_APP_STORE
ADMIN
ADMIN_APP_PROD
ADMIN_OWNER_PROD
APEX_240200
APEX_PUBLIC_ROUTER
APPQOSSYS
AUDSYS
AUTH_APP_PROD
AUTH_OWNER_PROD
BAASSYS
BLOCKCHAIN_APP
BLOCKCHAIN_OWNER
C##ADP$SERVICE
C##API
C##CLOUD$SERVICE
C##CLOUD_OPS
C##DATA$SHARE
C##DNSREST
C##DV_ACCT_ADMIN
C##DV_OWNER
C##OMLIDM
C##OMLREST2
C##QUEUE$SERVICE
C##RFS
C##TOTP_GENERATOR
C##TOTP_VALIDATOR
CHAT_APP_PROD
CHAT_OWNER_PROD
COMPANY_APP_PROD
COMPANY_OWNER_PROD
COURSE_APP_PROD
COURSE_OWNER_PROD
CTXSYS
DBSFWUSER
DBSNMP
DCAT_ADMIN
DGPDB_INT
DIP
DVF
DVSYS
EXAM_APP_PROD
EXAM_OWNER_PROD
FLOWS_FILES
GGADMIN
GGSHAREDCAP
GGSYS
GRAPH$METADATA
GRAPH$PROXY_USER
GSMADMIN_INTERNAL
GSMCATUSER
GSMUSER
JOB_APP_PROD
JOB_OWNER_PROD
KEYCLOAK_OWNER_PROD
LBACSYS
LBAC_TRIGGER
LEARNER_APP_PROD
LEARNER_OWNER_PROD
MASTER_DATA_APP_PROD
MASTER_DATA_OWNER_PROD
MDDATA
MDSYS
MEDIA_PROCESSOR_APP_PROD
MEDIA_PROCESSOR_OWNER_PROD
MTSSYS
NOTIFICATION_APP_PROD
NOTIFICATION_OWNER_PROD
OADC$PROXY
OADC_CATALOG_USER
ODI$PROXY
ODI_REPO_USER
OML$METADATA
OML$MODELS
OML$PROXY
OMLMOD$PROXY
ORDS_METADATA
ORDS_PLSQL_GATEWAY
ORDS_PUBLIC_USER
OUTLN
PYQSYS
REMOTE_SCHEDULER_AGENT
RMAN$CATALOG
RMAN$VPC
RQSYS
SH
SPATIAL$METADATA
SPATIAL$PROXY_USER
SSB
SYS
SYS$UMF
SYSBACKUP
SYSDG
SYSKM
SYSRAC
SYSTEM
TRAINING_APP_PROD
TRAINING_OWNER_PROD
VECSYS
XDB
XS$NULL""".split('\n')

for user in usernames:
    try:
        conn = oracledb.connect(user=user.strip(), password=password, config_dir=config_dir, wallet_location=config_dir, wallet_password=password, dsn=dsn)
        print(f"SUCCESS! Connected as: {user.strip()}")
        conn.close()
    except Exception as e:
        if 'ORA-01017' not in str(e) and 'ORA-28000' not in str(e) and 'ORA-46370' not in str(e):
            print(f"Error for {user}: {e}")
