[uwsgi]
module = app
callable = app
buffer-size=32768

master = true
processes = 4
threads = 2
socket = /tmp/uwsgi.sock
http-websockets = true
chmod-socket = 666
# gevent = 1000
vacuum = true
die-on-term = true
wsgi-disable-file-wrapper = true
